// Base de datos de letras (puedes ampliarla)
const lyricsDatabase = {
    'TODO CAMBIO': "Todo cambió\nCuando te vi, oh, oh, oh\nDe blanco y negro a color\nMe convertí\n\nY fue tan fácil\nQuererte tanto\nAlgo que no imaginaba\nFue entregarte mi amor\nCon una mirada\nOh, no, no, no, no\n\nTodo tembló\nDentro de mí (Yeh)\nEl universo escribió\nQue fueras para mí (Uh-uh, oh)\n\nY fue tan fácil\nQuererte tanto\nAlgo que no imaginaba\nFue perderme en tu amor\nSimplemente pasó\nY todo tuyo ya soy\n\nAntes que pase más\nTiempo contigo amor\nTengo que decir que eres el amor de mi vida\nAntes que te ame más\nEscucha por favor\nDéjame decir que todo te di\nY no hay cómo explicar\nPero, menos notar\nSimplemente, así lo sentí\nCuando te vi (Wooh)\n\nMe sorprendió\nTodo de ti (Uh-uh-uh, eh)\nDe blanco y negro a color\nMe convertí\n\nSé que no es fácil\nDecir te amo\nYo tampoco lo esperaba\nPero, así es el amor\nSimplemente pasó\nY todo tuyo ya soy\n\nAntes que pase más\nTiempo contigo amor\nTengo que decir que eres el amor de mi vida\nAntes que te ame más\nEscucha por favor\nDéjame decir que todo te di\nY no hay cómo explicar\nPero, menos notar\nSimplemente así lo sentí\nCuando te vi\n\nTodo cambió\nCuando te vi",
    'SOLO PARA TI': "Eres todo lo que pedía\nLo que mi alma vacía\nQuería sentir\n\nEres lo que tanto esperaba\nLo que en sueños buscaba\nY que en ti descubrí\n\nTu has llegado a encender\nCada parte de mi alma\nCada espacio de mi ser\n\nYa no tengo corazon\nNi ojos para nadie\nSolo para ti\n\nEres el amor de mi vida\nEl destino lo sabia\nY hoy te puso ante mi\nY cada vez que miro al pasado\n\nEs que entiendo que a tu lado\nSiempre pertenecí\n\nTu has llegado a encender\nCada parte de mi alma\nCada espacio de mi ser\nYa no tengo corazon\n\nNi ojos para nadie\nSolo para ti\nSolo para ti\nSolo para ti\n\nEsto es de verdad\nLo puedo sentir\nSe que mi lugar\nEs junto a ti\n\nEres todo lo que pedía\nLo que no conocía\nY que en ti descubrí\n",
    'COLECCIONISTA DE CANCIONES': "Uh-uh, oh-oh\n\nTú\nColeccionista de canciones\nDame razones\nPara vivir\n\nY así\nEn tu misterio poder\nDescubrir\nEl sentimiento eterno\n\nTú\nCon la luna en la cabeza\nEl lugar en donde empieza\nEl motivo y la ilusión de mi existir\n\nTan solo tú\nSolamente quiero que seas tú\nMi locura, mi tranquilidad y mi delirio\nMi compás y mi camino\n\nSolo tú\nSolamente quiero que seas tú\nMi locura, mi tranquilidad y mi delirio\nMi compás y mi camino\n\nSolo tú\nSolamente quiero que seas tú\nPongo en tus manos mi destino, porque vivo\nPara estar, siempre (siempre)\nSiempre (siempre)\n\nContigo, amor\n\nUh-uh, eh-yeh, eh-yeh\n\nTú\nColeccionista de canciones\nMil emociones\nSon para ti\n\nTú\nLo que soñé en mi vida entera\nQuédate en ella\nY hazme sentir\n\nY así\nIr transformando\nla magia\nDe tí\nEn un respiró del alma\n\nTú\nCon la luna en la cabeza\nEl lugar en donde empieza\nEl motivo y la ilusión de mi existir\n\nTan solo tú\nSolamente quiero que seas tú\nMi locura, mi tranquilidad y mi delirio\nMi compás y mi camino\n\nSolo tú\nSolamente quiero que seas tú\nPongo en tus manos mi destino, porque vivo\nPara estar siempre contigo\n\nYa no queda más espacio en mi interior\nHas llenado con tu luz cada rincón\nEs por ti que con el tiempo mi alma siente\nDiferente\n\nSolo tú\nSolamente\nquiero que seas tú\nMi locura, mi tranquilidad y mi delirio\nMi compás y mi camino\n\nSolo tú (solo tú)\nSolamente quiero que seas tú\nPongo en tus manos mi destino, porque vivo\nPara estar siempre (siempre)\nSiempre (siempre)\n\nContigo, amor\n\nAh-ah, ah, ah-ah, ah, ah\n\n",
    'BÉSAME': "Bésame\nA destiempo, sin piedad y en silencio\nBésame\nFrena el tiempo, haz crecer lo que siento\n\nBésame\nComo si el mundo se acabara después\nBésame\nY beso a beso pon el cielo al revés\nBésame\nSin razón, porque quiere el corazón\nBésame\n\nSiénteme\nEn el viento, mientras yo, muero lento\nBésame\nSin motivos, estaré, siempre contigo\n\nBésame\nComo si el mundo se acabara después\nBésame\nY beso a beso pon el cielo al revés\nBésame\nSin razón, porque quiere el corazón\nBésame\n\nBésame\nComo si el mundo se acabara después\nBésame\nY beso a beso pon el cielo al revés\nBésame\nSin razón, porque quiere el corazón\nBésame\n\nBésame así, sin compasión\nQuédate en mí, sin condición\nDame tan solo un motivo\nY me quedo yo\n\n",
    'ENTRE TUS ALAS': "Siempre fui esclavo de la libertad\nDe esos que saben flotar\nY que besan el cielo\n\nY hasta a que apareciste por ahí\nMe decidí aterrizar y quedarme en tu suelo\n\nDescubrí mi fe en tu ilusión<br>Mi alma reconoció tu voz y así\nSe fue detrás de ti mi corazón\n\nVuelo entre tus alas, despierto entre tu calma\nY mi paz (y mi paz), y mi razón\nViajo en tu mirada, me elevas\nSoy mejor de lo que fui por ti, amor\n\nY hasta hoy\nPensaba que era libertad\nEstaba en otro lugar\nY hoy la llevo por dentro\n\nMe asome al laberinto de tu amor\nAquí encontré mi verdad\nY en ti esta lo que quiero\n\nDescubrí mi fe en tu ilusión\nMi alma reconoció tu voz y así\nSe fue detrás de ti mi corazón\n\nVuelo entre tus alas, despierto entre tu calma\nY mi paz (y mi paz), y mi razón\n\nViajo en tu mirada me elevas\nSoy mejor de lo que fui por ti amor\n\nViajo en tu mirada me elevas\nSoy mejor de lo que fui por ti amor\n\nSiempre fui esclavo de la libertad\nContigo puedo tocar\nLo que soñé tanto tiempo\n\n",
    'TE CONFIESO': "Si la verdad te ofende\nSi te digo lo que siento y lo que mi alma no se atreve\nEs porque te quiero que te quiero hablar de frente\nPrefiero hoy herirte y no lo que hacen todos\nMentirte\n\nSi te digo que tocar tu mano, a veces, llega a confundirme\nQue la idea de cruzar el límite es irresistible\nLo digo aunque en el fondo pudiera arrepentirme\n\nTe confieso, es demasiado\nDescubrirme secuestrado\nTú\nMe hipnotizas\n\nAturdido, anestesiado\nContenido, congelado\nY tú\nNi te imaginas\n\nVoy arriesgarlo todo\nDe cualquier manera, estar sin ti es estar siempre perdiendo\nLo que grita este silencio adentro me está consumiendo\nTú dime si estoy solo o también lo estás sintiendo\n\nTe confieso, es demasiado\nDescubrirme secuestrado\nTú\nMe hipnotizas\nAturdido, anestesiado\nContenido, congelado\nY tú\nNi te imaginas\n\nSi la verdad te ofende\nSi te digo lo que siento y lo que mi alma no se atreve\nEs porque te quiero que te quiero hablar de frente\nPrefiero hoy herirte y no lo que hacen todos\nMentirte\n\n",
};

function goToSong(name, youtubeId) {
    const detailView = document.getElementById('song-detail');
    const content = document.getElementById('detail-content');

    // Construimos el contenido dinámicamente
    content.innerHTML = `
        <h1 style="margin: 20px 0;">${name}</h1>
        <div class="video-container">
            <iframe width="100%" height="315" src="https://www.youtube-nocookie.com/embed/${youtubeId}?origin=${window.location.origin}" frameborder="0" allow="autoplay; encrypted-media; picture-in-picture" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
        </div>
        <h3>Letra</h3>
        <p class="lyrics">${lyricsDatabase[name] || "Letra no disponible."}</p>
    `;

    // Animamos la entrada de la vista
    detailView.classList.add('active');
}

function closeDetail() {
    const detailView = document.getElementById('song-detail');
    detailView.classList.remove('active');
    
    // Limpiamos el video para que deje de sonar al cerrar
    document.getElementById('detail-content').innerHTML = "";
}